package com.reho.persistence.entities.enums;

public enum Nombre {

	LAVADO_ASPIRADO_COCHE_PEQUENO, LAVADO_ASPIRADO_CAMIONETA, LAVADO_TAPICERIA_COCHE_PEQUENO, PULIDO_FAROS,
	DETALLADO_COMPLETO, TRATAMIENTO_CERAMICO;

}
